"""initial schema

Revision ID: bc69bf40cd11
Revises: 
Create Date: 2025-12-30 14:33:56.774489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bc69bf40cd11'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_applied_offset', sa.Integer(), nullable=False),
    sa.Column('ruleshash', sa.String(), nullable=False),
    sa.Column('counter', sa.Integer(), nullable=False),
    sa.Column('phase', sa.Integer(), nullable=False),
    sa.Column('entropy', sa.Integer(), nullable=False),
    sa.Column('reveal_until_ms', sa.Integer(), nullable=False),
    sa.Column('cooldown_ms', sa.Integer(), nullable=True),
    sa.Column('updated_at_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rulesets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(), nullable=False),
    sa.Column('ruleset', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rulesets')
    op.drop_table('global_states')
    # ### end Alembic commands ###

