REDUCER_KAFKA_CONSUMER_BATCH_SIZE = 100
REDUCER_KAFKA_CLIENT_ID = "reducer-consumer"
REDUCER_KAFKA_GROUP_ID = "group.reducer"
REDUCER_COMMIT_INTERVAL_MS = 500

REDUCER_REDIS_STATE_UPDATE_CHANNEL = API_REDIS_STATE_UPDATE_CHANNEL = "state_updates:v1"
REDUCER_KAFKA_TOPIC = API_KAFKA_TOPIC = "press_button"

API_KAFKA_CLIENT_ID = "api-producer"
API_KAFKA_GLOBAL_KEY = "global"
